### PR TITLE
Fix for #3

### PR DESCRIPTION
**Pull request by MatrixCrawler**
- added gitignore
- renamed \TeamSpeak3\Helper\String to \TeamSpeak3\Helper\HelperString to avoid calss name conflict in PHP7

### CODE REVIEW

**Comment by lancepioch** [comment]
Please remove the .gitignore, everything else looks great, thank you.

**Comment by MatrixCrawler** [comment]
I added a version number to the composer. i was wondering why it was missing.
removed the .gitignore as requested

**Comment by t-richards** [comment]
From the official documentation about specifying the version in the `composer.json` file: https://getcomposer.org/doc/04-schema.md#version

> In most cases this [the version number] is not required and should be omitted
> 
> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.
> 
> Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

Since we're not monsters, we should instead rely on git tags to provide version numbers and always omit the `version` key from `composer.json`.

**Comment by arcdigital** [comment]
@t-richards is correct, this is why no version number was included originally (and should not be). I am going to revert this part of the change.

**Comment by arcdigital** [comment]
Also, @lancepioch in the future we shouldn't merge PRs with unnecessary changes. This PR should not have been merged with the "add gitignore" and "remove gitignore" commits.

**Pull request merged**
